import {
  Wallet,
  Coins,
  TrendingUp,
  GitBranch,
  Brain,
  Clock,
  Mail,
} from "lucide-react";

// Block definitions
export const blockTypes = {
  balancesByAddress: {
    id: "balancesByAddress",
    name: "Balances by Address",
    icon: Wallet,
    category: "Token",
    color: "bg-blue-500",
    description: "Get token balances for an address via The Graph",
  },
  transferEvents: {
    id: "transferEvents",
    name: "Transfer Events",
    icon: TrendingUp,
    category: "Token",
    color: "bg-blue-500",
    description: "Get token transfer events via The Graph",
  },
  conditional: {
    id: "conditional",
    name: "Conditional (IF)",
    icon: GitBranch,
    category: "Logic",
    color: "bg-purple-500",
    description: "Execute actions based on conditions",
  },
  tokenMetadata: {
    id: "tokenMetadata",
    name: "Token Metadata",
    icon: Coins,
    category: "Token",
    color: "bg-cyan-500",
    description: "Get token metadata via The Graph",
  },
  tokenInfo: {
    id: "tokenInfo",
    name: "Get Token Info",
    icon: Coins,
    category: "Token",
    color: "bg-green-500",
    description: "Get detailed token information via The Graph",
  },
  stake: {
    id: "stake",
    name: "Stake",
    icon: TrendingUp,
    category: "DeFi",
    color: "bg-orange-500",
    description: "Stake tokens on Sui or Oasis",
  },
  swap: {
    id: "swap",
    name: "Swap",
    icon: TrendingUp,
    category: "DeFi",
    color: "bg-orange-500",
    description: "Swap tokens on Sui or Oasis",
  },
  swapEvents: {
    id: "swapEvents",
    name: "Swap Events",
    icon: TrendingUp,
    category: "DeFi",
    color: "bg-cyan-500",
    description: "Get swap events data via The Graph",
  },
  embeddedWallet: {
    id: "embeddedWallet",
    name: "Embedded Wallet",
    icon: Wallet,
    category: "Wallet",
    color: "bg-indigo-500",
    description: "Sui zkLogin / Oasis Privy wallet",
  },
  aiExplanation: {
    id: "aiExplanation",
    name: "AI Explanation",
    icon: Brain,
    category: "AI",
    color: "bg-pink-500",
    description: "Get AI-powered insights and explanations",
  },
  sendEmail: {
    id: "sendEmail",
    name: "Send Email",
    icon: Mail,
    category: "Notifications",
    color: "bg-emerald-600",
    description: "Send an email via Resend API",
  },
  cronjob: {
    id: "cronjob",
    name: "Cronjob",
    icon: Clock,
    category: "Config",
    color: "bg-gray-500",
    description: "Schedule workflow execution (5 seconds interval)",
  },
  liquidityPools: {
    id: "liquidityPools",
    name: "Liquidity Pools",
    icon: TrendingUp,
    category: "DeFi",
    color: "bg-cyan-500",
    description: "Get liquidity pools data via The Graph",
  },
  nftActivities: {
    id: "nftActivities",
    name: "NFT Activities",
    icon: Coins,
    category: "Token",
    color: "bg-purple-600",
    description: "Get NFT activities and transfers via The Graph",
  },
  nftCollection: {
    id: "nftCollection",
    name: "NFT Collection",
    icon: Coins,
    category: "Token",
    color: "bg-purple-600",
    description: "Get NFT collection metadata via The Graph",
  },
};
